name: Build docker container with ssh

on:
  push:
    branches:
      - development

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        env:
          MAIL_USER: "API"
          MAIL_SENDER_EMAIL: "'Bojan Baltic' <mailtrap@demomailtrap.com>"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: MAIL_USER,MAIL_SENDER_EMAIL
          script: |
            cd ai-mambo/
            git checkout development
            git pull
            docker build -t nextjs-app .
            docker stop nextjs-app
            docker rm nextjs-app
            docker run -d -p 55614:3000 -e MAIL_USER=${MAIL_USER} -e MAIL_SENDER_EMAIL=${MAIL_SENDER_EMAIL} --name nextjs-app nextjs-app
            docker network connect backend_test nextjs-app
